dbt_spl:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 1
      type: "{{ env_var('DWH_TYPE') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      # private_key_path : "{{ env_var('SNOWFLAKE_KEY_PATH') }}" 
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PASSPHRASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
    dev_snowflake_workspace:
      type: snowflake
      role: tobi_training_role
      warehouse: tobi_training_wh
      database: tobi_training_db
      schema: public
      account: ''
      user: ''
  target: dev
