repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0
    hooks:
      - id: sqlfluff-lint
        additional_dependencies :
            - dbt-snowflake==1.9.1
            - dbt-core==1.9.1
            - sqlfluff-templater-dbt==3.4.0