name: push_trigger_sqlfluff

on: 
    push:
        branches-ignore:
        - 'main'
jobs:
    push:
        runs-on: ubuntu-latest

        steps:
        - name: Check out
          uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: "3.12.9"

        - name: Install packages
          run: |
            python -m pip install --upgrade pip
            pip install sqlfluff
            pip install sqlfluff-templater-dbt
            pip install dbt-snowflake

        - name: execute sqlfluff
          working-directory: dbt_spl
          run: |
            sqlfluff fix ./dbt_spl/models/mart/mart_kill_rate_and_abilities.sql